title: My Just the Docs Exercice
description: An initial exercice to using just the docs!
theme: just-the-docs

url: https://wjcchwsk.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/wjcchwsk/just-the-docs

logo: "/images/notes.png"
favicon_ico: "/images/notes.png"
color_scheme: dark
heading_anchors: true
